// Generated by LiveScript 1.5.0
(function(){
  var container, getContainer;
  container = require('./container.js');
  getContainer = container.getContainer;
  exports.getContainer = getContainer;
}).call(this);
